name: Datamodel-Code-Generator

on:
  pull_request:
    paths: 
    - 'src/lang/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datamodel-code-generator
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkout PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number}}
    - name: Run Code-Generator
      run: datamodel-codegen
    - name: Commit & Push Changes
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Datamodel-Code-Generator'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "datamodel-code-generator"
        git push
