name: Datamodel-Code-Generator

on:
  pull_request:
    paths: 
    - 'src/lang/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datamodel-code-generator
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkout PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number}}
    - name: Run Code-Generator
      run: | 
        RESULT=$(python datamodel.py)
        echo "Python result:"
        echo $RESULT
        if [[ RESULT ]]; then
          echo "Changes: $RESULT"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Nothing Changed"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
    - name: Commit & Push Changes
      if: ${{ steps.build.outputs.has_changes == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Datamodel-Code-Generator'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "datamodel-code-generator"
        git push